import { observer } from "mobx-react-lite";
import type { NextPage } from "next";
import Head from "next/head";
import Board from "../components/Board";
import Config from "../components/Config";
import useGame from "../hooks/useGame";

const Home: NextPage = () => {
  const game = useGame();

  return (
    <>
      <div>
        <Head>
          <title>Board AI</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Config />
          <Board
            width={game.width}
            height={game.height}
            type={game.boardType}
          />
        </div>
      </div>
    </>
  );
};

export default observer(Home);
